# build
script:
  - 'phantomjs scripts/qunit-runner.js test/index.html'
  - './script/cibuild.sh'

# environment
language: ruby
rvm:
  - '2.0.0'

branches:
  only:
    - 'master'

notifications:
  email: false
