before_install:
  - sudo apt-get install python-setuptools
  - 'easy_install http://closure-linter.googlecode.com/files/closure_linter-latest.tar.gz'

# build
script:
  - 'phantomjs script/qunit-phantomjs-runner/runner.js test/index.html'
  - './script/cibuild.sh'

# environment
language: ruby
rvm:
  - '2.0.0'

branches:
  only:
    - 'master'

notifications:
  email: false
