before_install:
  - 'svn checkout http://closure-linter.googlecode.com/svn/trunk/ script/closure-linter'

# build
script:
  - 'phantomjs script/qunit-phantomjs-runner/runner.js test/index.html'
  - './script/closure-linter/closure_linter/gjslint.py -r ./js'
  - './script/cibuild.sh'

# environment
language: ruby
rvm:
  - '2.0.0'

branches:
  only:
    - 'master'

notifications:
  email: false
