before_install:
  - 'sudo apt-get update -qq'
  - 'sudo apt-get install -qq closure-linter'

# build
script:
  - 'phantomjs script/qunit-phantomjs-runner/runner.js test/index.html'
  - 'gjslint -r ./js'
  - './script/cibuild.sh'

# environment
language: ruby
rvm:
  - '2.0.0'

branches:
  only:
    - 'master'

notifications:
  email: false
