before_install:
  - 'npm install jslint jshint -g'

# build
script:
  - './script/branding.sh'
  - 'phantomjs script/qunit-phantomjs-runner/runner.js test/index.html'
  - './script/jslint.sh'
  - './script/cibuild.sh'

# environment
language: ruby
rvm:
  - '2.0.0'

branches:
  only:
    - 'master'

notifications:
  email: false
